name = "zonepack"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cfcc5fef2bca2d55653f86cb250f9769ced5341705aaf6df47a547cb2775b11f"

[versions]
forge = "47.3.6"
minecraft = "1.20.1"
